config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  get 'cart', to: 'cart#show'
  get 'search', to: 'menu#search'
  resources :categories
  get 'menu', to: 'menu#index'
  devise_for :users
  resources :products
  root 'pages#home'
  get 'catering', to: 'pages#catering'
  get 'info', to: 'pages#info'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal

    def subtotal 
        order_items.collect {|order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum 
    end

    private 
    
    def set_subtotal
        self[:subtotal] = subtotal 
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price] 
    else
      product.price 
    end
  end

  def total 
    return unit_price * quantity
  end

  private 

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity 
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_one_attached :image
    has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items 
    
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:heading, :body, :display)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_cats
  def index
    @page = 'menu'
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def search
    query = params[:search]

    results = Product.where('name LIKE ?', "%#{query}%")
    if params[:filter] == 'Select Filter'
      @products = results
    else
      # 'Dairy Free' -> 'Dairy_Free' -> 'dairy_free' -> :dairy_free
      symbol = params[:filter].gsub(/ /, '_').downcase!.to_sym
      # @products = results.where(:dairy_free => true)
      @products = results.where(symbol => true)
    end
  end

  private

  def set_cats
    @cats = Category.all.where(display: true)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order
  def create
    @order_item = @order.order_items.new(order_params)
    @order.save 
    session[:order_id] = @order.id
  end

  def update
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items 
  end

  private

  def order_params
    params.require(:order_item).permit(:product_id, :quantity)
  end

  def set_order
    @order = current_order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page = 'home'
  end

  def catering
    @page = 'catering'
  end

  def info
    @page = 'info'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.category = Category.find(params[:product][:category_id])

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :vegan, :image, :category_id, :vegetarian, :available, :catering, :featured)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_order
        if Order.find_by_id(session[:order_id]).nil?
            Order.new 
        else
            Order.find_by_id(session[:order_id])
        end
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of $#{current_order.subtotal}", cart_path %>

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>
    <h3><%= item.product.name %></h3>
    <h3><%= item.product.price %></h3>
    <%= form_with model: item do |f|%>
        <%= f.hidden_field :product_id, value: item.product.id %>
        <%= f.number_field :quantity, value: item.quantity.to_i %>
        <%= f.submit "Update Cart" %>
        <%= link_to "Remove Items", item, method: :delete, remote: true %>
    <% end %>
    <h2>Subtotal: <%= item.total %></h2>
<% end %>

<h3>Your current order has a total of: <%= current_order.subtotal %></h3>

app/views/cart/show.html.erb
<div id="cart-item">
    <%=  render 'cart_items' %>
</div>

<hr>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Heading:</strong>
    <%= category.heading %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= category.body %>
  </p>

  <p>
    <strong>Display:</strong>
    <%= category.display %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :heading %>
    <%= f.input :body %>
    <%= f.input :display %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/_links.html.erb
<div class="col-2">
    <h5 class="link-container">
        <%= link_to "Home", root_path, class: "link #{@page == 'home' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Menu", menu_path, class: "link #{@page == 'menu' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Catering", catering_path, class: "link #{@page == 'catering' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Info", info_path, class: "link #{@page == 'info' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Customer Reviews", '', class: "link #{@page == 'reviews' ? 'active' : ''}" %>
    </h5>
</div>

app/views/layouts/_title.html.erb
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text:ital@1&display=swap" rel="stylesheet"> 
<div class="title-card">
    <h1 class="title-text">
        moshi moshi!
    </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Climate+Crisis&family=Golos+Text:wght@500&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="<%= @page %>-page">
      <div class="row page-container">
        <%= render 'layouts/links' %>
        <div class="col-8">
          <% unless @page == "home" %>
          <%= render 'layouts/title' %>
          <% end %>
        <%= yield %>
        </div>
        <div class="col-2"></div>
      </div>
    </div> 
  </body>
</html>

app/views/menu/_products.html.erb
<div class="row">
    <% @cats.each do |cat| %>
    <% if cat.products.where(featured: true).first.image.attached? %>
        <%= image_tag(cat.products.where(featured: true).first.image, class:'img-fluid') %>
    <% end %>
    <div class="col-12">
        <h1 style="text-align:center;"><%= cat.heading %></h1>
        <hr />
    </div>
    <% @products.each do |product| %>
    <% if product.category == cat %>
        <div class="col-4">
            <h5>
                <%= product.name %>
            </h5>
            <p>
                <%= product.description %>
            </p>
            <span><%= product.price %><%= " | Available for catering" if product.catering %></span>
            <%= form_with model: @order_item, local: false do |f| %>
                <%= f.hidden_field :product_id, value: product.id %>
                <%= f.number_field :quantity, value: 1, min: 1 %>
                <%= f.submit "Add to cart" %>
            <% end %>
        </div>
    <% end %>
    <% end %>
    <% end %>
    
</div>

app/views/menu/index.html.erb
<div class="menu-container">
    <div class="row">
        <div class="col-12">
            <%= form_tag(search_path, method: "get", remote: true) do %>
            <div class="input-group mb-5">
                <div class="col-8" style="padding:0">
                    <%= text_field_tag :search, '', class:'form-control', placeholder: 'Search...', onkeydown:'clickSubmit();'%>
                </div>
                <div class="col-4" style="padding:0">
                    <%= select_tag "filter", options_for_select(['Select Filter', 
                    'Vegan', 
                    'Vegetarian']), class:'custom-select', onchange:'clickSubmit()'%>
                    <%= submit_tag "Search", class:'btn btn-dark', id:'search_submit'%>
                </div>
            </div>
            <% end %>
        </div>
    </div>
    <div id="menu-products-container">
        <%= render 'menu/products'%>
    </div>
</div>

<script>
    function clickSubmit() {
        $("#search_submit").click();
    }
</script>

app/views/menu/search.js.erb
$("#menu-products-container").html("<%= j render 'menu/products' %>" );

app/views/order_items/create.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");

app/views/order_items/destroy.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/order_items/update.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/pages/catering.html.erb
<h1>Pages#catering</h1>
<p>Find me in app/views/pages/catering.html.erb</p>

app/views/pages/home.html.erb
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text:ital@1&display=swap" rel="stylesheet"> 
    <h1 class="home-title-text">
        moshi moshi!
    </h1>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :vegan, style: "display: block" %>
    <%= form.check_box :vegan %>
  </div>

  <div>
    <%= form.label :vegetarian, style: "display: block" %>
    <%= form.check_box :vegetarian %>
  </div>

  <div>
    <%= form.label :available, style: "display: block" %>
    <%= form.check_box :available %>
  </div>

  <div>
    <%= form.label :catering, style: "display: block" %>
    <%= form.check_box :catering %>
  </div>

  <div>
    <%= form.label :featured, style: "display: block" %>
    <%= form.check_box :featured %>
  </div>
  
  <div class="field">
    <%= form.label :category %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :heading, @product.category.id ) %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Vegan:</strong>
    <%= product.vegan %>
  </p>

  <p>
    <strong>Vegetarian:</strong>
    <%= product.vegetarian %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= product.available %>
  </p>

  <p>
    <strong>Catering:</strong>
    <%= product.catering %>
  </p>

  <p>
    <strong>Featured:</strong>
    <%= product.featured %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>